# Generated by Django 3.2.3 on 2021-06-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='view',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
