# Generated by Django 3.2.3 on 2021-06-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_auto_20210608_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_one_score', models.DecimalField(decimal_places=10, max_digits=11)),
                ('category_two_score', models.DecimalField(decimal_places=10, max_digits=11)),
                ('category_three_score', models.DecimalField(decimal_places=10, max_digits=11)),
                ('view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='views.view')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=560)),
                ('view_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='views.viewreview')),
            ],
        ),
    ]
